name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                ports:
                    - 3306:3306
                env:
                    MYSQL_HOST: 127.0.0.1
                    MYSQL_DATABASE: peerwatch
                    MYSQL_ROOT_PASSWORD: root
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
            LOCAL_DB_HOST: 127.0.0.1
            LOCAL_DB_USER: root
            LOCAL_DB_PASS: root
            LOCAL_DB_PORT: 3306
            ACCESS_SECRET: randomsecret
            EMAIL_USER: ${{ secrets.EMAIL_USER }}
            EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup node
            uses: actions/setup-node@v2
            with:
              node-version: 16.x
          - name: Setup Redis
            uses: supercharge/redis-github-action@1.2.0
            with:
                redis-version: 6
          - name: Setup MySQL
            run: |
                mysql --host 127.0.0.1 --port 3306 -uroot -proot < ./sql/peerwatch_users.sql
                mysql --host 127.0.0.1 --port 3306 -uroot -proot < ./sql/peerwatch_rooms.sql
                mysql --host 127.0.0.1 --port 3306 -uroot -proot < ./sql/peerwatch_users_in_rooms.sql
          - name: Install dependencies
            run: npm run install-all
          - name: Cypress tests
            run: npm run cypress-test
          - name: Mocha Chai tests
            run: npm run mocha-test
